version: 1

trail:
  artifacts:
    - name: nginx
      attestations:
        - name: pull-request
          type: pull_request
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
