
fullnameOverride: "nginx"

replicaCount: 1

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

containers:
  - name: nginx
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
    env:
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_K8S_PORT: "19661"

  # livenessProbe:
  #   path: /alive
  #   port: 80
  # readinessProbe:
  #   path: /ready
  #   port: 80
