
fullnameOverride: "nginx"

replicaCount: 1

containers:
  - name: nginx
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
  # livenessProbe:
  #   path: /alive?
  #   port: 80
  # readinessProbe:
  #   path: /ready?
  #   port: 80

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
