
fullnameOverride: "nginx"

replicaCount: 1

service:
  port: 80

containers:
  - name: nginx
    image: cyberdojo/nginx
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 96Mi
  # livenessProbe:
  #   path: /alive?
  #   port: 80
  # readinessProbe:
  #   path: /ready?
  #   port: 80

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
