name: Main

on:
  push:
    branches:
      - gh-actions

jobs:
  pre-build:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.prep.outputs.tag }}
    steps:

    - uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo "TAG=${TAG}" >> ${GITHUB_ENV}
        echo ::set-output name=tag::${TAG}

  build:
    needs: [pre-build]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/build.yml@master
    with:
      tag: ${{ needs.pre-build.outputs.tag }}
      docker_context: ./
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      registry: 244531986313.dkr.ecr.eu-central-1.amazonaws.com
      service_name: nginx
      gh_actions_iam_role_name: gh_actions_services
  
  deploy-staging:
    needs: [pre-build, build]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/deploy.yml@master
    with:
      tagged_image: 244531986313.dkr.ecr.eu-central-1.amazonaws.com/nginx:${{ needs.pre-build.outputs.tag }}
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      gh_actions_iam_role_name: gh_actions_services
      environment_url: https://beta.cyber-dojo.org
      environment_name: staging

  #deploy-prod:
  #  needs: [pre-build, build, deploy-staging]
  #  environment: 
  #    name: production
  #    url: https://prod.cyber-dojo.org
  #  uses: cyber-dojo/creator/.github/workflows/deploy.yml@master
  #  with:
  #    tagged_image: 274425519734.dkr.ecr.eu-central-1.amazonaws.com/creator:${{ needs.pre-build.outputs.tag }}
  #    AWS_ACCOUNT_ID: 274425519734
  #    AWS_REGION: eu-central-1
